import "@styles/global.css";

import type { ReactNode } from "react";
import { Providers } from "./provider";

export const metadata = {
  title: "Next15 TypeScript Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
