import "@styles/global.css";

import { AppSidebar } from "@requests/components/app-sidebar";
import { SiteHeader } from "@requests/components/site-header";
import { SidebarInset, SidebarProvider } from "@requests/components/ui/sidebar";
import type { ReactNode } from "react";
import { Providers } from "./provider";

export const metadata = {
  title: "Next15 TypeScript Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <SidebarProvider>
            <AppSidebar variant="inset" />
            <SidebarInset>
              <SiteHeader />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
